services:
  backend:
    build:
      context: ./server
    container_name: wealthx-backend
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client/vite-project
    container_name: wealthx-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend